version : '3.8'
services:
  db: 
    container_name: grouplink_database
    image: postgres:11.6-alpine
    restart: always
    command: postgres -c logging_collector=on -c log_destination=stderr 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=database
      - POSTGRES_INITDB_ARGS=--locale=en_US.UTF-8
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore
    
    ports:
      - "5232:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
