version : '3.8'
services:
  db: 
    container_name: binance_robot
    image: postgres:11.6-alpine
    restart: always
    command: postgres -c logging_collector=on -c log_destination=stderr 
    environment:
      - POSTGRES_USER=binance
      - POSTGRES_PASSWORD=binance
      - POSTGRES_DB=binance
      - POSTGRES_HOST=localhost
      - POSTGRES_INITDB_ARGS=--locale=en_US.UTF-8
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore
    
    ports:
      - "5832:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
